// 请认真对待 proto 文件的文件名，MessageName.proto
// 故此包名, 命名为 mobile.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: mobile.proto

package protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MobileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brand string `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"` // 品牌
}

func (x *MobileInfo) Reset() {
	*x = MobileInfo{}
	mi := &file_mobile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MobileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MobileInfo) ProtoMessage() {}

func (x *MobileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mobile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MobileInfo.ProtoReflect.Descriptor instead.
func (*MobileInfo) Descriptor() ([]byte, []int) {
	return file_mobile_proto_rawDescGZIP(), []int{0}
}

func (x *MobileInfo) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

var File_mobile_proto protoreflect.FileDescriptor

var file_mobile_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x22, 0x22, 0x0a, 0x0a, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mobile_proto_rawDescOnce sync.Once
	file_mobile_proto_rawDescData = file_mobile_proto_rawDesc
)

func file_mobile_proto_rawDescGZIP() []byte {
	file_mobile_proto_rawDescOnce.Do(func() {
		file_mobile_proto_rawDescData = protoimpl.X.CompressGZIP(file_mobile_proto_rawDescData)
	})
	return file_mobile_proto_rawDescData
}

var file_mobile_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mobile_proto_goTypes = []any{
	(*MobileInfo)(nil), // 0: protoc.MobileInfo
}
var file_mobile_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mobile_proto_init() }
func file_mobile_proto_init() {
	if File_mobile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mobile_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mobile_proto_goTypes,
		DependencyIndexes: file_mobile_proto_depIdxs,
		MessageInfos:      file_mobile_proto_msgTypes,
	}.Build()
	File_mobile_proto = out.File
	file_mobile_proto_rawDesc = nil
	file_mobile_proto_goTypes = nil
	file_mobile_proto_depIdxs = nil
}
